export const dynamic_data = {
    field_height: {
        "N": "Normal",
        "4-6": "4ft 6in",
        "4-7": "4ft 7in",
        "4-8": "4ft 8in",
        "4-9": "4ft 9in",
        "4-10": "4ft 10in",
        "4-11": "4ft 11in",
        "5": "5ft",
        "5-1": "5ft 1in",
        "5-2": "5ft 2in",
        "5-3": "5ft 3in",
        "5-4": "5ft 4in",
        "5-5": "5ft 5in",
        "5-6": "5ft 6in",
        "5-7": "5ft 7in",
        "5-8": "5ft 8in",
        "5-9": "5ft 9in",
        "5-10": "5ft 10in",
        "5-11": "5ft 11in",
        "6": "6ft",
        "6-1": "6ft 1in",
        "6-2": "6ft 2in",
        "6-3": "6ft 3in",
        "6-4": "6ft 4in",
        "6-5": "6ft 5in",
        "6-6": "6ft 6in",
        "6-7": "6ft 7in",
        "6-8": "6ft 8in",
        "6-9": "6ft 9in",
        "6-10": "6ft 10in",
        "6-11": "6ft 11in",
        "7": "7ft"
       },
       ac_for: {
        'M': "Myself",
        'D': "Daughter",
        'S': "Son",
        'I': "Sister",
        'B': "Brother",
        'R': "Relative",
        'F': "Friend",
      },
      field_gender: {
        'M': "Male",
        'F': "Female",
      },

      field_Religion:{
        'Hin-Beng': "Hindu - Bengali",
        'Hin-Mar': "Hindu - Marwari ",
        'Hin-Tam': "Hindu - Tamil  ",
        'Hin-Pun': "Hindu - Punjabi  ",
        'Hin-Guj': "Hindu - Gujarati  ",
        'Hin-Nep': "Hindu - Nepali  ",
        'Hin-Bali': "Hindu - Balinese   ",
        'Hin-Sind': "Hindu - Sindhi   ",
        'Hin-Oth': "Hindu - Others   ",
        'Mu_Shi': "Muslim - Shia",
        'Mu_Sun': "Muslim - Sunni",
        'Mu_Oth': "Muslim - Others",
        'Chr': "Christian",
        'Sik': "Sikh",
        'Ja_Dig': "Jain - Digambar",
        'Ja_Shw': "Jain - Shwetambar",
        'Ja_Oth': "Jain - Others",
        'Par': "Parsi",
        'Bud': "Buddhist",
        'Int-Rel': "Inter-Religion"
       },
       
       field_weight: {
        '41': "41 Kg",
        '42': "42 Kg",
        '43': "43 Kg",
        '44': "44 Kg",
        '45': "45 Kg",
        '46': "46 Kg",
        '47': "47 Kg",
        '48': "48 Kg",
        '49': "49 Kg",
        '50': "50 Kg",
        '51': "51 Kg",
        '52': "52 Kg",
        '53': "53 Kg",
        '54': "54 Kg",
        '55': "55 Kg",
        '56': "56 Kg",
        '57': "57 Kg",
        '58': "58 Kg",
        '59': "59 Kg",
        '60': "60 Kg",
        '61': "61 Kg",
        '62': "62 Kg",
        '63': "63 Kg",
        '64': "64 Kg",
        '65': "65 Kg",
        '66': "66 Kg",
        '67': "67 Kg",
        '68': "68 Kg",
        '69': "69 Kg",
        '70': "70 Kg",
        '71': "71 Kg",
        '72': "72 Kg",
        '73': "73 Kg",
        '74': "74 Kg",
        '75': "75 Kg",
        '76': "76 Kg",
        '77': "77 Kg",
        '78': "78 Kg",
        '79': "79 Kg",
        '80': "80 Kg",
        '81': "81 Kg",
        '82': "82 Kg",
        '83': "83 Kg",
        '84': "84 Kg",
        '85': "85 Kg",
        '86': "86 Kg",
        '87': "87 Kg",
        '88': "88 Kg",
        '89': "89 Kg",
        '90': "90 Kg",
        '91': "91 Kg",
        '92': "92 Kg",
        '93': "93 Kg",
        '94': "94 Kg",
        '95': "95 Kg",
        '96': "96 Kg",
        '97': "97 Kg",
        '98': "98 Kg",
        '99': "99 Kg",
        '100': "100 Kg",
        '101': "101 Kg",
        '102': "102 Kg",
        '103': "103 Kg",
        '104': "104 Kg",
        '105': "105 Kg",
        '106': "106 Kg",
        '107': "107 Kg",
        '108': "108 Kg",
        '109': "109 Kg",
        '110': "110 Kg",
        '111': "111 Kg",
        '112': "112 Kg",
        '113': "113 Kg",
        '114': "114 Kg",
        '115': "115 Kg",
        '116': "116 Kg",
        '117': "117 Kg",
        '118': "118 Kg",
        '119': "119 Kg",
        '120': "120 Kg",
        '121': "121 Kg",
        '122': "122 Kg",
        '123': "123 Kg",
        '124': "124 Kg",
        '125': "125 Kg",
        '126': "126 Kg",
        '127': "127 Kg",
        '128': "128 Kg",
        '129': "129 Kg",
        '130': "130 Kg",
        '131': "131 Kg",
        '132': "132 Kg",
        '133': "133 Kg",
        '134': "134 Kg",
        '135': "135 Kg",
        '136': "136 Kg",
        '137': "137 Kg",
        '138': "138 Kg",
        '139': "139 Kg",
        '140': "140 Kg",
       },
       field_body_type: {
        'S': "Slim",
        'A': "Athletic",
        'Aver': "Average ",
        'H': "Heavy "
        },
        field_marital_status: {
        'N': "Never Married",
        'W': "Widowed",
        'D': "Divorced Awaiting divorce",
        'A': "Awaiting divorce",
       },
   field_disability: {
        'N': "Normal",
        'P': "Physically Challenged"
       },
   field_Eating_Habits: {
        'V': "Vegetarian",
        'N': "Non Vegetarian ",
        'E': "Eggetarian",
       },

   field_Drinking_Habits: {
        'N': "No",
        'D': "Drinks Socially",
        'Y': "Yes"
       },

    field_Smoking_Habits : {
    'N': "No",
    'O': "Occasionally   ",
    'Y': "Yes"
    },
    
    field_country:  {
        'Ind': "India",
        'uk': "U.K."
        },

    field_Employed_in: {
        'G': "Government/PSU",
        'P': "Private",
        'B': "Business",
        'D': "Defence",
        'S': "Self Employed",
        'N': "Not working"
        },

        field_Father_Occupation: {
            'E': "Employed",
            'B': "Business Man",
            'P': "Professional",
            'R': "Retired",
            'N': "Not Employed",
            'Passed': "Passed Away"
           },


          field_Mother_Occupation: {
            'H': "Homemaker",
            'E': "Employed",
            'B': "Business Woman",
            'P': "Professional",
            'R': "Retired",
            'Passed': "Passed Away"
           },

           field_family_status: {
            'M': "Middle class",
            'U': "Upper middle class",
            'R': "Rich",
            'A': "Affluent"
           },
           field_family_value: {
            'O': "Orthodox",
            'T': "Traditional",
            'M': "Moderate",
            'L': "Liberal"
           },

           field_family_type:{
            'J': "Joint",
            'N': "Nuclear"
           },

           field_No_Brother:  {
            '0': "none",
            '1': "1",
            '2': "2",
            '3': "3",
            '4': "4",
            '5': "5",
            '6': "5+",
           },
           field_No_Sister: {
            '0': "none",
            '1': "1",
            '2': "2",
            '3': "3",
            '4': "4",
            '5': "5",
            '6': "5+",
           },

           field_Family_Location:  {
            'S': "Same as my Location",
            'D': "Different Location"
           },
           field_Hobbies_Interests: {
            'Actin': "Acting",
            'Adve': "Adventure sports",
            'Alt': "Alternative healing / Medicine",
            'Art': "Art / Handicraft",
            'Astr': "Astrology",
            'Bak': "Baking",
            'Bike': "Bike / Car enthusiast",
            'Bir_wat': "Bird watching",
            'Danc': "Dancin"
           },

           field_Music:  {
            'Chris': "Christian / Gospel",
            'Clas': "Classical",
            'Carna': "Classical - Carnatic",
            'Coun': "Country",
            'Deamet': "Death metal",
            'Devot': "Devotional",
            'Dis': "Disco",
            'EDM': "EDM (Electronic Dance Music)",
            'Filson': "Film songs",
            'Folmus': "Folk music",
            'Fusi': "Fusion",
            'Ghaz': "Ghazals"
             },

             field_field_Sports : {
                'Aerobics': "Aerobics",
                'AmerFoot': "American Football",
                'Arch': "Archery",
                'Badm': "Badminton",
                'Basebal': "Baseball",
                'Baskbal': "Basketball",
                'Bil': "Billiards / Snooker / Pool",
                'Bowl': "Bowling",
                'Box': "Boxing",
                'Cri': "Cricket",
                'Cyc': "Cycling",
                'Foot': "Football"
               },

               field_Preferred_Movies: {
                'Act': "Action",
                'Ani': "Anime",
                'Cla': "Classics",
                'Com': "Comedy",
                'Docum': "Documentaries",
                'Dra': "Drama",
                'Epi': "Epics",
                'Fan': "Fantasy",
                'Hor': "Horror",
                'Mov': "Movie fanatic",
                'Neo': "Neo-noir",
                'Noco': "Non-commercial / Art",
                'Roman': "Romantic",
                'RomanCom': "Romantic Comedies",
                'Sci_Fi': "Sci-Fi",
                'Shofil': "Short films",
                'Thri': "Thriller / Suspense",
                'Worcin': "World cinema"
               },

               field_Spoken_Languages : {
                'Ben': "Bengali",
                'Eng': "English",
                'Hin': "Hindi"
                }
          
          

  };

